### PR TITLE
Update README.md; add warnings.

### PR DESCRIPTION
**Pull request by sirocyl**
... You're gonna brick so many people.
I, and other developers, would recommend just not releasing this, to be fair - some going as far as to say that it should be taken down for being malicious...
but I'm going to at least make a very clear and pointed warning to you, the developers, as well as the users, that "the usual 3DS homebrew users" will be bricking their consoles and whining about it. Hopefully some words in the README will alleviate that issue a bit.

### CODE REVIEW

**Comment by d0k3** [comment]
Thanks, @sirocyl! These are strong arguments you're bringing up. It's also the first time ever I get a readme pull request for an unreleased, unfinished project.

Can you give me some more info? Like the exact, reproducable steps to follow to brick with this?

**Comment by sirocyl** [comment]
Hey, sorry about the accusatory language and all. I was really tired when I wrote this, and a little upset in general. Maybe it won't have as bad an impact as I thought it would, though some developers have made some pressing arguments otherwise.

Ultimately, it's a developer tool more than anything, and it's your project. I shouldn't be yelling at you for making something someone might find useful.

If you don't think it's necessary to include any such warning, close this. There is the definite likelihood of a badly-behaved or unaware payload causing FIRM corruption, but anyone who decides to use this, should know anyway. It's not like releases are being compiled, or builds advertised on GBATemp or anything.

If people still use it and manage to brick things, maybe they should've known not to use it the way they did.,

**Comment by d0k3** [comment]
It's alright, but it's good you noticed.

In fact, I agree that the readme needs some additional info, and that's were it comes to the actual changes in this pull request. While part of it is well written, and I'd very much like to take it, other stuff sounds like you haven't even tried OldLoader before writing this - thus my earlier question.

This project is also not yet finished, so stuff will still change, and normally I'd only do a proper readme after a project has reached at least a near finalized state.

Let me suggest two ways to go about it, cause this will still need changes. First, we will keep this pr open for the time being. Once I made some changes and I'm ready to take this, I can (1) contact you again and ask for the required changes or (2) do these changes myself and change what needs changed, still attributing this commit back to you.

If you in the meantime have some ideas on how to improve on OldLoader, contributions are always welcome.

**Comment by d0k3** [comment]
Okay, we removed the boot9strap magic from this, effectively disallowing boots from any software that checks for it (that includes Luma), for safety reasons. I may still use some parts of your edits, and I hope you're okay with this.

Also, thanks, contributions are always welcome!

**Pull request closed without merging**
